import type { BrainConfig } from '../config.js';
import type { Db } from '../db/index.js';
import { latestBrief, saveBrief } from '../core/briefs.js';
import { listCommits, parseCommitFiles, type CommitFile } from '../core/commits.js';
import { countChatTurns } from '../core/chat.js';
import { countDecisions, extractDecisionCandidates, listDecisions } from '../core/decisions.js';
import { buildTimeline } from '../core/timeline.js';
import { lastEventId, recentEvents } from '../core/events.js';
import type { ChatTurnRow, CommitRow, DecisionRow, EventRow, ProjectRow, TimelineEntry } from '../core/types.js';
import { gitStatusShort } from '../git/git.js';
import { hasOllamaModel, listOllamaModels } from '../embeddings/embedder.js';
import { createOllamaLlm } from '../llm/ollama.js';
import { log } from '../util/logger.js';
import { formatDay, plural, relativeTime, truncate } from '../util/format.js';
import { buildProjectProfile, type ProjectProfile } from './profile.js';
import {
  analyzeProjectState,
  projectImprovementNarrative,
  projectScopeNarrative,
  projectStateNarrative,
  type ProjectState,
} from './state.js';
import { detectStack, detectTestCommand } from './stack.js';
import { detectInvokingShell, shellHookFiles, type SupportedShell } from '../capture/shellHook.js';

/** A file touched by the recent commits, most-touched first. */
export interface ChangedFile {
  path: string;
  commits: number;
  add: number;
  del: number;
}

/** A top-level directory grouping of recent work, so a brief can name the focus. */
export interface WorkArea {
  name: string;
  commits: number;
  files: number;
  add: number;
  del: number;
}

/**
 * What the capture pipeline currently looks like from the outside. Without this
 * the user cannot tell the difference between "quiet week" and "nothing is being
 * captured", which is exactly the confusion a thin brief creates.
 */
export interface CaptureHealth {
  events: number;
  commits: number;
  chatTurns: number;
  decisions: number;
  shellHooks: SupportedShell[];
  invokingShell: SupportedShell | null;
  lastEventTs: number | null;
  hint: string | null;
}

export interface BriefData {
  project: ProjectRow;
  generatedAt: number;
  timeline: TimelineEntry[];
  commits: CommitRow[];
  decisions: DecisionRow[];
  recentCommands: EventRow[];
  recentChat: ChatTurnRow[];
  touchedFiles: string[];
  dirtyFiles: string[];
  failingCommands: string[];
  stack: string[];
  testCommand: string | null;
  stats: {
    events: number;
    commits: number;
    chatTurns: number;
    decisions: number;
    firstTs: number | null;
  };
  watermark: number;
  /** Present on briefs generated by the CLI (absent in hand-built fixtures). */
  profile?: ProjectProfile;
  changedFiles?: ChangedFile[];
  areas?: WorkArea[];
  capture?: CaptureHealth;
  /** Where the project stands, read off the repository itself. */
  state?: ProjectState;
}

export interface BriefOptions {
  maxEvents?: number;
  since?: number;
  /** Skip the LLM even when one is configured. */
  heuristicOnly?: boolean;
  /** Gather capture diagnostics (skipped for the cheap auto-brief path). */
  withHealth?: boolean;
}

async function gatherBriefData(db: Db, project: ProjectRow, options: BriefOptions): Promise<BriefData> {
  const maxEvents = options.maxEvents ?? 200;
  const since = options.since ?? 0;
  const generatedAt = Date.now();

  const timeline = buildTimeline(db, { projectId: project.id, limit: maxEvents, since });
  // More commits than we display: the narrative needs enough history to name the
  // theme of the recent work rather than just the newest commit.
  const commits = listCommits(db, project.id, 20);
  const decisions = listDecisions(db, project.id, 10);
  const recentCommands = recentEvents(db, project.id, 40, ['cmd']);
  const touched = buildTimeline(db, { projectId: project.id, limit: maxEvents, since, kinds: ['file'] });

  const touchedFiles: string[] = [];
  const seen = new Set<string>();
  for (const entry of touched) {
    const file = entry.text.replace(/^\w+\s+/, '').trim();
    if (file && !seen.has(file)) {
      seen.add(file);
      touchedFiles.push(file);
    }
    if (touchedFiles.length >= 15) break;
  }

  const failingCommands: string[] = [];
  const retried = new Set<string>();
  for (const row of recentCommands) {
    let cmd = '';
    try {
      cmd = String((JSON.parse(row.payload) as { cmd?: string }).cmd ?? '');
    } catch {
      cmd = '';
    }
    if (!cmd) continue;
    if ((row.exit_code ?? 0) === 0) {
      retried.add(cmd);
    } else if (!retried.has(cmd) && failingCommands.length < 5 && !failingCommands.includes(cmd)) {
      failingCommands.push(cmd);
    }
  }

  const dirtyFiles = await gitStatusShort(project.path).catch(() => []);

  const firstRow = db
    .prepare('SELECT MIN(ts) AS ts FROM events WHERE project_id = ?')
    .get(project.id) as { ts: number | null } | undefined;
  const lastEventRow = db
    .prepare('SELECT MAX(ts) AS ts FROM events WHERE project_id = ?')
    .get(project.id) as { ts: number | null } | undefined;

  const stats = {
    events: (db.prepare('SELECT COUNT(*) AS n FROM events WHERE project_id = ?').get(project.id) as { n: number }).n,
    commits: (db.prepare('SELECT COUNT(*) AS n FROM commits WHERE project_id = ?').get(project.id) as { n: number }).n,
    chatTurns: countChatTurns(db, project.id),
    decisions: countDecisions(db, project.id),
    firstTs: firstRow?.ts ?? null,
  };

  const profile = await buildProjectProfile(db, project).catch(() => undefined);

  const data: BriefData = {
    project,
    generatedAt,
    timeline,
    commits,
    decisions,
    recentCommands,
    recentChat: [],
    touchedFiles,
    dirtyFiles,
    failingCommands,
    stack: profile?.stack ?? detectStack(project.path),
    testCommand: profile?.testCommand ?? detectTestCommand(project.path),
    stats,
    watermark: lastEventId(db, project.id),
    profile,
    changedFiles: aggregateChangedFiles(commits),
    areas: groupAreas(commits),
    // Reading the repo is the only way to answer "was I done or interrupted?",
    // so it happens for every brief, health or not.
    state: await analyzeProjectState(project, commits).catch(() => undefined),
  };

  if (options.withHealth !== false) {
    const hooked: SupportedShell[] = [];
    for (const shell of ['bash', 'zsh', 'powershell'] as SupportedShell[]) {
      if (shellHookFiles(shell).length > 0) hooked.push(shell);
    }
    const invokingShell = await detectInvokingShell().catch(() => null);
    data.capture = {
      events: stats.events,
      commits: stats.commits,
      chatTurns: stats.chatTurns,
      decisions: stats.decisions,
      shellHooks: hooked,
      invokingShell,
      lastEventTs: lastEventRow?.ts ?? null,
      hint: captureHint(hooked, invokingShell, stats.events),
    };
  }

  return data;
}

/** Files touched by the most recent commits, ranked by how often they appear. */
export function aggregateChangedFiles(commits: CommitRow[], limit = 8): ChangedFile[] {
  const stats = new Map<string, ChangedFile>();
  for (const commit of commits) {
    for (const file of parseCommitFiles(commit.files)) {
      const entry = stats.get(file.path) ?? { path: file.path, commits: 0, add: 0, del: 0 };
      entry.commits += 1;
      entry.add += file.add;
      entry.del += file.del;
      stats.set(file.path, entry);
    }
  }
  return [...stats.values()]
    .sort(
      (a, b) =>
        b.commits - a.commits || b.add + b.del - (a.add + a.del) || a.path.localeCompare(b.path),
    )
    .slice(0, limit);
}

/** Group recent work by top-level directory, so a brief can name the focus. */
export function groupAreas(commits: CommitRow[], limit = 4): WorkArea[] {
  const areas = new Map<string, { commits: number; files: Set<string>; add: number; del: number }>();
  for (const commit of commits) {
    const counted = new Set<string>();
    for (const file of parseCommitFiles(commit.files)) {
      const slash = file.path.indexOf('/');
      const name = slash > 0 ? file.path.slice(0, slash) : 'root files';
      const entry = areas.get(name) ?? { commits: 0, files: new Set<string>(), add: 0, del: 0 };
      entry.files.add(file.path);
      entry.add += file.add;
      entry.del += file.del;
      if (!counted.has(name)) {
        entry.commits += 1;
        counted.add(name);
      }
      areas.set(name, entry);
    }
  }
  return [...areas.entries()]
    .map(([name, entry]) => ({
      name,
      commits: entry.commits,
      files: entry.files.size,
      add: entry.add,
      del: entry.del,
    }))
    .sort(
      (a, b) =>
        b.commits - a.commits || b.add + b.del - (a.add + a.del) || a.name.localeCompare(b.name),
    )
    .slice(0, limit);
}

const VAGUE_SUBJECTS = new Set([
  'idk',
  'idk anymore',
  'update',
  'updates',
  'wip',
  'minor',
  'minor change',
  'minor changes',
  'changes',
  'stuff',
  'misc',
  'fix',
  'fixes',
  'test',
  'tests',
  'oops',
  'temp',
  'tmp',
  'save',
  'progress',
  'initial commit',
  'first commit',
]);

/** True when a commit subject carries no information about *what* changed. */
export function isVagueSubject(subject: string): boolean {
  const clean = subject.trim().toLowerCase().replace(/[.!\s]+$/, '');
  if (clean.length === 0) return true;
  if (VAGUE_SUBJECTS.has(clean)) return true;
  // "spectral", "v3 model", "graph changes" — a word or two tells us nothing.
  return clean.split(/\s+/).length <= 2 && clean.length <= 18;
}

export function commitSubject(commit: CommitRow): string {
  return (commit.message ?? '').split('\n')[0]?.trim() ?? '';
}

/** "a, b and c" */
function listPhrase(items: string[]): string {
  if (items.length <= 1) return items[0] ?? '';
  return `${items.slice(0, -1).join(', ')} and ${items[items.length - 1]}`;
}

/** Biggest files of a commit, largest diff first. */
function topFilesOf(commit: CommitRow, limit = 3): string[] {
  return [...parseCommitFiles(commit.files)]
    .sort((a, b) => b.add + b.del - (a.add + a.del))
    .slice(0, limit)
    .map((file) => file.path);
}

/** What the user most plausibly wants to do next, from the evidence at hand. */
function nextStep(data: BriefData): string | null {
  const failing = data.failingCommands[0];
  if (failing) return `re-run \`${truncate(failing, 60)}\`, which is still failing`;
  const dirty = data.dirtyFiles[0];
  if (dirty) return `finish the uncommitted change in \`${truncate(dirty.replace(/^\S+\s+/, ''), 50)}\``;
  const busiest = data.changedFiles?.[0];
  if (busiest) return `open \`${truncate(busiest.path, 54)}\` — it is in ${plural(busiest.commits, 'recent commit')}`;
  if (data.testCommand) return `run \`${data.testCommand}\` to see where things stand`;
  return null;
}

/**
 * The "where you left off" prose.
 *
 * Every sentence is derived from captured facts — commit times, per-file line
 * counts, the working tree, failing commands — so it reads like a handover
 * note instead of a list, and never invents anything the history cannot prove.
 */
export function activityNarrative(data: BriefData): string[] {
  const paragraphs: string[] = [];
  const commits = data.commits;
  const areas = data.areas ?? [];
  const files = data.changedFiles ?? [];
  const last = commits[0];

  if (!last) {
    paragraphs.push(
      `Nothing is committed in **${data.project.name}** yet, so there is no work history to summarise.`,
    );
  } else {
    const lastFiles = topFilesOf(last, 3);
    const diff = last.insertions + last.deletions;
    const firstSentence =
      `You were last active **${relativeTime(last.ts, data.generatedAt)}** — commit \`${last.hash.slice(0, 7)}\` ${
        commitSubject(last) ? `"${truncate(commitSubject(last), 60)}"` : '(empty message)'
      }, changing ${plural(last.files_changed, 'file')}${diff > 0 ? ` (+${last.insertions}/-${last.deletions} lines)` : ''}` +
      (lastFiles.length > 0 ? `: ${lastFiles.map((file) => `\`${truncate(file, 46)}\``).join(', ')}.` : '.');
    paragraphs.push(firstSentence);

    if (commits.length > 1) {
      const span = formatDay(commits[commits.length - 1]?.ts ?? last.ts);
      const areaPhrase =
        areas.length > 0
          ? ` Most of that went into ${listPhrase(
              areas.slice(0, 3).map((area) => `**${area.name}** (${plural(area.commits, 'commit')})`),
            )}.`
          : '';
      const busiest = files[0];
      const filePhrase = busiest
        ? ` The busiest file is \`${truncate(busiest.path, 52)}\` (${plural(busiest.commits, 'commit')}${
            busiest.add + busiest.del > 0 ? `, +${busiest.add}/-${busiest.del} lines` : ''
          }).`
        : '';
      paragraphs.push(
        `That was the newest of ${plural(commits.length, 'commit')} since ${span}.${areaPhrase}${filePhrase}`,
      );
    }

    const biggest = [...commits].sort(
      (a, b) => b.insertions + b.deletions - (a.insertions + a.deletions),
    )[0];
    if (biggest && biggest.hash !== last.hash && biggest.insertions + biggest.deletions > 0) {
      const inBiggest = topFilesOf(biggest, 2);
      paragraphs.push(
        `The single largest change was \`${biggest.hash.slice(0, 7)}\` ${
          commitSubject(biggest) ? `"${truncate(commitSubject(biggest), 50)}"` : ''
        } — +${biggest.insertions}/-${biggest.deletions} across ${plural(
          biggest.files_changed,
          'file',
        )}${inBiggest.length > 0 ? ` (${inBiggest.map((file) => `\`${truncate(file, 40)}\``).join(', ')})` : ''}.`,
      );
    }

    const sample = commits.slice(0, 8);
    const vague = sample.filter((commit) => isVagueSubject(commitSubject(commit)));
    if (vague.length >= Math.max(2, Math.ceil(sample.length / 2))) {
      paragraphs.push(
        `Your recent commit messages are one-liners (${vague
          .slice(0, 3)
          .map((commit) => `"${truncate(commitSubject(commit), 22)}"`)
          .join(', ')}), so this is reconstructed from the files each commit touched. \`brain log "decided X because Y"\` or a captured shell session makes the next brief much richer.`,
      );
    }
  }

  const state: string[] = [];
  if (data.dirtyFiles.length > 0) {
    state.push(
      `**${plural(data.dirtyFiles.length, 'file')} uncommitted** (${data.dirtyFiles
        .slice(0, 4)
        .map((file) => `\`${truncate(file, 44)}\``)
        .join(', ')}) — that is most likely exactly where you stopped.`,
    );
  } else if (last) {
    state.push('The working tree is clean, so all of that is committed.');
  }
  if (data.failingCommands.length > 0) {
    state.push(
      `Still broken: ${data.failingCommands
        .slice(0, 3)
        .map((cmd) => `\`${truncate(cmd, 60)}\``)
        .join(', ')}${data.failingCommands.length === 1 ? ' failed and was never re-run successfully.' : ' failed and were never re-run successfully.'}`,
    );
  }
  if (data.touchedFiles.length > 0) {
    state.push(
      `Live edits were last seen in ${data.touchedFiles.slice(0, 3).map((file) => `\`${truncate(file, 44)}\``).join(', ')}.`,
    );
  }
  if (state.length > 0) paragraphs.push(state.join(' '));

  const events = data.capture?.events ?? data.stats.events;
  if (events === 0) {
    paragraphs.push(
      'No shell or editor activity has been captured for this project yet, so this is reconstructed from git alone — open a new terminal after installing the shell hooks and the brief will include commands, edits and failures.',
    );
  }
  const next = nextStep(data);
  if (next) paragraphs.push(`**Pick up with:** ${next}.`);

  return paragraphs;
}

function captureHint(hooked: SupportedShell[], invoking: SupportedShell | null, events: number): string | null {
  if (hooked.length === 0) {
    return 'no shell hook installed — commands are never captured. Fix: brain shell install';
  }
  if (invoking && !hooked.includes(invoking)) {
    return `your ${invoking} shell has no hook, so commands typed there are not captured. Fix: brain shell install`;
  }
  if (events === 0) {
    return 'no commands or file touches captured yet — open a new terminal after installing hooks, then run something';
  }
  return null;
}

/** Deterministic, offline brief. Always available; the fallback of record. */
export function heuristicBrief(data: BriefData): string {
  const lines: string[] = [];
  const { project } = data;
  lines.push(`# ${project.name} — where you left off`);
  lines.push('');
  lines.push(
    `_generated ${relativeTime(data.generatedAt)} · ${plural(data.stats.commits, 'commit')}${
      data.stats.firstTs ? ` since ${formatDay(data.stats.firstTs)}` : ''
    }_`,
  );
  lines.push('');

  /* Identity, stack and layout are written as prose in "What it is" below. */
  const profile = data.profile;

  /* -------- what this project is, in its own words -------- */
  const scope = projectScopeNarrative({
    projectName: project.name,
    summary: profile?.summary ?? project.summary ?? '',
    stack: profile?.stack ?? data.stack,
    languages: profile?.languages ?? [],
    topLevel: profile?.topLevel ?? [],
    gitRemote: profile?.gitRemote ?? project.git_remote,
    branch: profile?.branch ?? null,
    scopeDocs: data.state?.scopeDocs ?? [],
  });
  if (scope.length > 0) {
    lines.push('## What it is');
    for (const paragraph of scope) lines.push(paragraph, '');
  }

  /* -------- the current state: what is done and what is not -------- */
  const stateProse = data.state
    ? projectStateNarrative(data.state, {
        generatedAt: data.generatedAt,
        projectName: project.name,
        dirtyFiles: data.dirtyFiles,
        totalCommits: data.stats.commits,
        events: data.capture?.events ?? data.stats.events,
      })
    : [];
  if (stateProse.length > 0) {
    lines.push('## Where it stands');
    for (const paragraph of stateProse) lines.push(paragraph, '');
  }

  /* -------- where the project itself says it could go next -------- */
  const ideas = data.state ? projectImprovementNarrative(data.state) : [];
  if (ideas.length > 0) {
    lines.push('## What could come next');
    for (const idea of ideas) lines.push(`- ${idea}`);
    lines.push('');
  }

  /* -------- loose ends: only what is genuinely dangling -------- */
  const threads: string[] = [];
  for (const cmd of data.failingCommands) {
    threads.push(`\`${truncate(cmd, 90)}\` failed and was never re-run successfully`);
  }
  const lastCommand = data.recentCommands[0];
  if (lastCommand) {
    let cmd = '';
    try {
      cmd = String((JSON.parse(lastCommand.payload) as { cmd?: string }).cmd ?? '');
    } catch {
      cmd = '';
    }
    if (cmd) {
      threads.push(
        `the last command captured was \`${truncate(cmd, 80)}\`${
          lastCommand.exit_code ? ` (exit ${lastCommand.exit_code})` : ''
        }, ${relativeTime(lastCommand.ts, data.generatedAt)}`,
      );
    }
  }
  if (data.dirtyFiles.length > 0) {
    threads.push(
      `${plural(data.dirtyFiles.length, 'file')} uncommitted — ${data.dirtyFiles
        .slice(0, 4)
        .map((line) => truncate(line, 50))
        .join(', ')}`,
    );
  }
  if (data.touchedFiles.length > 0) {
    threads.push(
      `live edits recently in ${data.touchedFiles.slice(0, 4).map((file) => truncate(file, 50)).join(', ')}`,
    );
  }
  if (data.testCommand) threads.push(`test command: \`${data.testCommand}\``);
  if (threads.length > 0) {
    lines.push('## Loose ends');
    for (const thread of threads) lines.push(`- ${thread}`);
    lines.push('');
  }

  /* -------- decisions, but only when there are any -------- */
  if (data.decisions.length > 0) {
    lines.push('## Decisions');
    for (const decision of data.decisions.slice(0, 6)) {
      lines.push(`- ${truncate(decision.text, 160)}${decision.tags ? ` (${decision.tags})` : ''}`);
    }
    lines.push('');
  }

  /* -------- capture health, kept short: this is operational, not content -------- */
  if (data.capture) {
    const capture = data.capture;
    const hooks =
      capture.shellHooks.length > 0 ? capture.shellHooks.join(', ') : 'none installed';
    lines.push('## Capture');
    lines.push(
      `${plural(capture.events, 'event')} captured · shell hooks: ${hooks}${
        capture.invokingShell ? ` (this shell: ${capture.invokingShell})` : ''
      }`,
    );
    if (capture.hint) lines.push(capture.hint);
    lines.push('');
  }

  lines.push(
    '_Everything above is derived from the repository. Full history: `brain timeline` · questions: `brain ask "…"`._',
  );
  return lines.join('\n');
}

/** Files of a commit with their line counts, biggest diff first. */
function filesForCommit(commit: CommitRow): CommitFile[] {
  return [...parseCommitFiles(commit.files)].sort((a, b) => b.add + b.del - (a.add + a.del));
}

/** `path +12/-3`, or just `path` when git reported no line counts (binary). */
function fileWithCounts(file: CommitFile): string {
  return file.add + file.del > 0 ? `${file.path} +${file.add}/-${file.del}` : file.path;
}

/** Compact digest handed to the LLM; keeps the prompt small and factual. */
export function renderDigest(data: BriefData): string {
  const lines: string[] = [];
  lines.push(`Project: ${data.project.name} (${data.project.path})`);
  if (data.profile?.summary) lines.push(`Summary: ${data.profile.summary}`);
  const stack = data.profile?.stack ?? data.stack;
  if (stack.length > 0) lines.push(`Stack: ${stack.join(', ')}`);
  if (data.profile && data.profile.languages.length > 0) {
    lines.push(`Languages: ${data.profile.languages.map((entry) => `${entry.language} (${entry.files})`).join(', ')}`);
  }
  if (data.profile?.topLevel.length) {
    lines.push(`Layout: ${data.profile.topLevel.map((entry) => entry.name).join(' ')}`);
  }
  const remote = data.profile?.gitRemote ?? data.project.git_remote;
  if (remote) lines.push(`Git remote: ${remote}`);
  lines.push(`Generated: ${new Date(data.generatedAt).toISOString()}`);
  lines.push(
    `Totals: ${data.stats.events} events, ${data.stats.commits} commits, ${data.stats.chatTurns} chat turns`,
  );
  lines.push('');
  lines.push('Recent timeline (newest first):');
  for (const entry of data.timeline.slice(0, 60)) {
    lines.push(`- [${new Date(entry.ts).toISOString()}] (${entry.kind}) ${truncate(entry.text, 200)}`);
  }
  if (data.areas && data.areas.length > 0) {
    lines.push('');
    lines.push('Where the work went (top-level areas, biggest first):');
    for (const area of data.areas) {
      lines.push(
        `- ${area.name}: ${area.commits} commits, ${area.files} files, +${area.add}/-${area.del} lines`,
      );
    }
  }
  if (data.commits.length > 0) {
    lines.push('');
    lines.push('Recent commits (newest first, with the files each one changed):');
    for (const commit of data.commits.slice(0, 10)) {
      const files = filesForCommit(commit)
        .slice(0, 6)
        .map((file) => fileWithCounts(file))
        .join(', ');
      lines.push(
        `- ${commit.hash.slice(0, 7)} ${truncate(commit.message ?? '', 140)} (+${commit.insertions}/-${commit.deletions}, ${
          commit.files_changed
        } files${files ? `: ${files}` : ''})`,
      );
    }
  }
  if (data.state) {
    lines.push('');
    lines.push('What the project is (its own words, from the repository):');
    for (const doc of data.state.scopeDocs) lines.push(`- ${doc.file}: ${truncate(doc.excerpt, 700)}`);
    if (data.state.featureRows.length > 0) {
      lines.push('');
      lines.push('Features/phases the documents list (done or not):');
      for (const row of data.state.featureRows) {
        lines.push(`- [${row.done ? 'done' : 'open'}] ${row.name}${row.note ? ` — ${row.note}` : ''} (${row.file})`);
      }
    }
    const stateProse = projectStateNarrative(data.state, {
      generatedAt: data.generatedAt,
      projectName: data.project.name,
      dirtyFiles: data.dirtyFiles,
      totalCommits: data.stats.commits,
      events: data.capture?.events ?? data.stats.events,
    });
    if (stateProse.length > 0) {
      lines.push('');
      lines.push('Project state read off the repository (facts, not guesses):');
      for (const paragraph of stateProse) lines.push(paragraph.replace(/\*\*/g, ''));
    }
    const ideas = projectImprovementNarrative(data.state, 5);
    if (ideas.length > 0) {
      lines.push('');
      lines.push('Ideas the project itself lists for what comes next:');
      for (const idea of ideas) lines.push(`- ${idea.replace(/\*\*/g, '')}`);
    }
  }
  if (data.commits.length > 0) {
    lines.push('');
    lines.push('Locally computed summary (factual; rewrite it in fluent prose, never contradict it):');
    for (const paragraph of activityNarrative(data)) lines.push(paragraph.replace(/\*\*/g, ''));
  }
  if (data.decisions.length > 0) {
    lines.push('');
    lines.push('Logged decisions:');
    for (const decision of data.decisions) lines.push(`- ${truncate(decision.text, 200)}`);
  }
  if (data.dirtyFiles.length > 0) {
    lines.push('');
    lines.push('Uncommitted changes:');
    for (const file of data.dirtyFiles.slice(0, 10)) lines.push(`- ${file}`);
  }
  if (data.failingCommands.length > 0) {
    lines.push('');
    lines.push('Commands that failed and were not re-run successfully:');
    for (const cmd of data.failingCommands) lines.push(`- ${cmd}`);
  }
  if (data.profile?.readme) {
    lines.push('');
    lines.push('README (excerpt):');
    lines.push(data.profile.readme.slice(0, 1500));
  }
  return lines.join('\n');
}

export function briefPrompt(digest: string, projectName: string): string {
  return [
    `You are maintaining a local "second brain" for a developer. Below is raw captured activity for the project "${projectName}".`,
    'Write the handover note this developer should read after a break. Friendly and concrete, like a colleague briefing them. Prose, not tables or inventories.',
    'Rules:',
    '- Markdown, no preamble, no code fences. 220 words max.',
    '- Use exactly three sections: "## What it is", "## Where it stands", "## What could come next".',
    '- "What it is": 2-3 sentences on what the project is for and how it is built, using the project own README/PRD/overview wording. Do not list directories.',
    '- "Where it stands": 3-5 sentences. Say whether work stopped at a natural finishing point or mid-task, which parts are implemented (use the feature/phase list), what the project own documents claim about progress, and what is still open (unchecked backlog items, TODO/FIXME markers, new modules without tests). Mention how long ago the last work was.',
    '- "What could come next": up to three bullet points, drawn from the project own roadmap/future-work lists. Attribute each one to the document it came from. If the repository lists nothing, omit the section rather than inventing ideas.',
    '- Do not list commits, files changed or per-file line counts: that history is available with `brain timeline`.',
    '- Never invent features, files, commands or dates the data does not contain.',
    '',
    digest,
  ].join('\n');
}

/** Why an LLM summary was not used, so the CLI can tell the user what to fix. */
export interface LlmOutcome {
  attempted: boolean;
  used: boolean;
  model: string;
  reason: string | null;
}

export interface GeneratedBrief {
  projectId: number;
  text: string;
  generator: string;
  watermark: number;
  createdAt: number;
  llm: LlmOutcome;
}

export async function generateBrief(
  db: Db,
  config: BrainConfig,
  project: ProjectRow,
  options: BriefOptions = {},
): Promise<GeneratedBrief> {
  const data = await gatherBriefData(db, project, options);
  let text = '';
  let generator = 'heuristic';
  const llm: LlmOutcome = { attempted: false, used: false, model: config.llm.model, reason: null };

  if (config.llm.provider === 'none') {
    llm.reason = 'disabled in config (llm.provider = none)';
  } else if (options.heuristicOnly) {
    llm.reason = 'skipped for this run (--heuristic)';
  } else {
    llm.attempted = true;
    const models = await listOllamaModels(config.llm.ollamaUrl);
    if (models === null) {
      llm.reason = `Ollama not reachable at ${config.llm.ollamaUrl} — start it with: ollama serve`;
    } else if (!hasOllamaModel(models, config.llm.model)) {
      llm.reason = `model "${config.llm.model}" is not installed — run: ollama pull ${config.llm.model}`;
    } else {
      const client = createOllamaLlm({
        url: config.llm.ollamaUrl,
        model: config.llm.model,
        timeoutMs: config.llm.timeoutMs,
      });
      const digest = renderDigest(data);
      const generated = await client.generate(briefPrompt(digest, project.name), {
        temperature: 0.2,
        maxTokens: 400,
      });
      if (generated.trim().length > 0) {
        text = generated.trim();
        generator = client.name;
        llm.used = true;
      } else {
        llm.reason = 'the model returned an empty response';
      }
    }
    if (!llm.used) log.debug(`llm brief skipped: ${llm.reason}`);
  }

  if (text.trim().length === 0) {
    text = heuristicBrief(data);
    generator = 'heuristic';
  }

  const id = saveBrief(db, {
    projectId: project.id,
    summaryText: text,
    generatedAt: data.generatedAt,
    eventWatermark: data.watermark,
    generator,
  });
  log.debug(`saved brief ${id} for ${project.name} (${generator})`);
  return { projectId: project.id, text, generator, watermark: data.watermark, createdAt: data.generatedAt, llm };
}

/** True when it is time to auto-brief this project again (cd-trigger throttle). */
export function shouldAutoBrief(db: Db, projectId: number, minIntervalMinutes: number): boolean {
  const brief = latestBrief(db, projectId);
  if (!brief) return true;
  const ageMs = Date.now() - brief.generated_at;
  return ageMs >= Math.max(0, minIntervalMinutes) * 60_000;
}

/** Turn commit subjects into suggested decision entries. */
export function suggestDecisionsFromCommits(db: Db, projectId: number, limit = 10): string[] {
  const commits = listCommits(db, projectId, 100);
  const suggestions: string[] = [];
  for (const commit of commits) {
    const subject = (commit.message ?? '').split('\n')[0] ?? '';
    for (const candidate of extractDecisionCandidates(subject)) {
      if (!suggestions.includes(candidate)) suggestions.push(candidate);
    }
    if (suggestions.length >= limit) break;
  }
  return suggestions.slice(0, limit);
}
